import React from "react";
import ReportViewer from "../components/ReportViewer";
import { FilePlus2 } from "lucide-react";

const Reports = () => {
  return (
    <div className="bg-gradient-to-br from-white to-gray-50 p-8 rounded-2xl shadow-sm border border-gray-200 hover:shadow-md transition-all">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between mb-6 gap-3">
        <div>
          <h1 className="text-3xl font-bold text-gray-800 flex items-center gap-2">
            📄 Reports
          </h1>
          <p className="text-gray-600 text-sm mt-1">
            Access and manage all automatically generated log reports here.
          </p>
        </div>

        <button className="flex items-center gap-2 bg-blue-600 text-white px-5 py-2 rounded-lg shadow-sm hover:bg-blue-700 transition">
          <FilePlus2 size={18} />
          Generate Report
        </button>
      </div>

      {/* Description */}
      <div className="bg-white border border-gray-100 rounded-xl shadow-sm p-5 mb-6">
        <p className="text-gray-700 leading-relaxed">
          Below are your most recent system reports generated by LogEasy. You can open, preview, or
          download them anytime. Each report includes system activity summaries, error trends, and
          compliance details.
        </p>
      </div>

      {/* Report Viewer */}
      <div className="bg-white border border-gray-100 rounded-xl shadow-sm p-6">
        <h2 className="text-xl font-semibold mb-3 text-gray-800">📊 Available Reports</h2>
        <ReportViewer />
      </div>
    </div>
  );
};

export default Reports;
